# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-20 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbackformapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
    ]
